
export const mealsData = [
  {
    id: 1,
    name: "Papas Fritas",
    image: require("../assets/dishes/papas_fritas.jpg"),
    difficulty: "Baja",
    time: "20'",
    proteins: "5g",
    calories: "312",
    price: 2500,
    ingredients: [
      { emoji: "🥔", name: "Papas", quantity: 300, unit: "g" },
      { emoji: "🧂", name: "Sal", quantity: 1, unit: "pizca" },
      { emoji: "🥄", name: "Aceite", quantity: 200, unit: "ml" },
    ],
    steps: [
      "Lavar y pelar las papas.",
      "Cortarlas en bastones.",
      "Freír en aceite caliente hasta que estén doradas.",
      "Escurrir y agregar sal al gusto.",
    ],
  },
  {
    id: 2,
    name: "Ensalada César",
    image: require("../assets/dishes/ensalada_cesar.jpg"),
    difficulty: "Baja",
    time: "15'",
    proteins: "12g",
    calories: "180",
    price: 4200,
    ingredients: [
      { emoji: "🥬", name: "Lechuga romana", quantity: 100, unit: "g" },
      { emoji: "🍗", name: "Pechuga de pollo", quantity: 120, unit: "g" },
      { emoji: "🧀", name: "Queso parmesano", quantity: 30, unit: "g" },
      { emoji: "🍞", name: "Crutones", quantity: 50, unit: "g" },
      { emoji: "🥣", name: "Aderezo César", quantity: 30, unit: "ml" },
    ],
    steps: [
      "Lavar y cortar la lechuga.",
      "Cocinar el pollo a la plancha y cortarlo en tiras.",
      "Agregar crutones y queso parmesano.",
      "Incorporar el aderezo y mezclar bien antes de servir.",
    ],
  },
  {
    id: 3,
    name: "Pollo al Horno",
    image: require("../assets/dishes/pollo_al_horno.jpg"),
    difficulty: "Media",
    time: "45'",
    proteins: "35g",
    calories: "400",
    price: 5500,
    ingredients: [
      { emoji: "🍗", name: "Pollo", quantity: 250, unit: "g" },
      { emoji: "🥔", name: "Papas", quantity: 200, unit: "g" },
      { emoji: "🧄", name: "Ajo", quantity: 2, unit: "dientes" },
      { emoji: "🌿", name: "Hierbas", quantity: 1, unit: "cda" },
      { emoji: "🥄", name: "Aceite de oliva", quantity: 20, unit: "ml" },
    ],
    steps: [
      "Precalentar el horno a 200°C.",
      "Colocar el pollo y las papas en una bandeja.",
      "Añadir ajo, hierbas y aceite de oliva.",
      "Hornear por 40-45 minutos hasta que esté dorado.",
    ],
  },
  //-------------------
  {
    id: 4,
    name: "Arroz con Pollo",
    image: require("../assets/dishes/arroz_con_pollo.jpg"),
    difficulty: "Media",
    time: "40'",
    proteins: "28g",
    calories: "520",
    price: 4800,
    ingredients: [
      { emoji: "🍗", name: "Pollo", quantity: 200, unit: "g" },
      { emoji: "🍚", name: "Arroz", quantity: 150, unit: "g" },
      { emoji: "🫑", name: "Pimentón", quantity: 50, unit: "g" },
      { emoji: "🧅", name: "Cebolla", quantity: 50, unit: "g" },
      { emoji: "🥣", name: "Caldo", quantity: 250, unit: "ml" },
    ],
    steps: [
      "Sofreír cebolla y pimentón.",
      "Añadir el pollo en trozos y dorar.",
      "Agregar arroz y mezclar.",
      "Incorporar el caldo y cocinar hasta que el arroz esté listo.",
    ],
  },
  {
    id: 5,
    name: "Panqueques con Manjar",
    image: require("../assets/dishes/panqueques_manjar.jpg"),
    difficulty: "Baja",
    time: "25'",
    proteins: "6g",
    calories: "350",
    price: 1800,
    ingredients: [
      { emoji: "🥚", name: "Huevos", quantity: 2, unit: "u" },
      { emoji: "🥛", name: "Leche", quantity: 200, unit: "ml" },
      { emoji: "🌾", name: "Harina", quantity: 100, unit: "g" },
      { emoji: "🍯", name: "Manjar", quantity: 80, unit: "g" },
    ],
    steps: [
      "Mezclar leche, huevos y harina.",
      "Cocinar panqueques en un sartén caliente.",
      "Rellenar cada panqueque con manjar.",
      "Enrollar y servir.",
    ],
  },
  {
    id: 6,
    name: "Tortilla de Papas",
    image: require("../assets/dishes/tortilla_papas.jpg"),
    difficulty: "Baja",
    time: "30'",
    proteins: "10g",
    calories: "280",
    price: 2300,
    ingredients: [
      { emoji: "🥔", name: "Papas", quantity: 250, unit: "g" },
      { emoji: "🥚", name: "Huevos", quantity: 3, unit: "u" },
      { emoji: "🧅", name: "Cebolla", quantity: 40, unit: "g" },
      { emoji: "🫒", name: "Aceite", quantity: 20, unit: "ml" },
    ],
    steps: [
      "Picar y freír las papas con cebolla.",
      "Batir los huevos y mezclar con las papas.",
      "Cocinar a fuego medio hasta que cuaje.",
      "Dar vuelta y dorar por ambos lados.",
    ],
  },
  {
    id: 7,
    name: "Spaghetti Boloñesa",
    image: require("../assets/dishes/spaghetti_bolonesa.jpg"),
    difficulty: "Media",
    time: "35'",
    proteins: "22g",
    calories: "450",
    price: 5000,
    ingredients: [
      { emoji: "🍝", name: "Spaghetti", quantity: 150, unit: "g" },
      { emoji: "🥩", name: "Carne molida", quantity: 200, unit: "g" },
      { emoji: "🍅", name: "Tomate triturado", quantity: 200, unit: "g" },
      { emoji: "🧅", name: "Cebolla", quantity: 50, unit: "g" },
    ],
    steps: [
      "Cocinar los fideos al dente.",
      "Sofreír cebolla y añadir la carne.",
      "Agregar tomate y cocinar 15 minutos.",
      "Mezclar con los fideos y servir.",
    ],
  },
  {
    id: 8,
    name: "Omelette",
    image: require("../assets/dishes/omelette.jpg"),
    difficulty: "Baja",
    time: "10'",
    proteins: "14g",
    calories: "160",
    price: 1200,
    ingredients: [
      { emoji: "🥚", name: "Huevos", quantity: 2, unit: "u" },
      { emoji: "🧀", name: "Queso", quantity: 30, unit: "g" },
      { emoji: "🫑", name: "Pimentón", quantity: 20, unit: "g" },
    ],
    steps: [
      "Batir los huevos.",
      "Agregar rellenos y mezclar.",
      "Cocinar en un sartén por ambos lados.",
    ],
  },
  {
    id: 9,
    name: "Sopa de Tomate",
    image: require("../assets/dishes/sopa_tomate.jpg"),
    difficulty: "Baja",
    time: "20'",
    proteins: "4g",
    calories: "150",
    price: 2800,
    ingredients: [
      { emoji: "🍅", name: "Tomates", quantity: 300, unit: "g" },
      { emoji: "🧄", name: "Ajo", quantity: 1, unit: "diente" },
      { emoji: "🌿", name: "Albahaca", quantity: 5, unit: "g" },
    ],
    steps: [
      "Cocinar los tomates con ajo.",
      "Licuar la mezcla.",
      "Agregar albahaca y servir caliente.",
    ],
  },
  {
    id: 10,
    name: "Tacos de Pollo",
    image: require("../assets/dishes/tacos_pollo.jpg"),
    difficulty: "Media",
    time: "25'",
    proteins: "20g",
    calories: "390",
    price: 4500,
    ingredients: [
      { emoji: "🍗", name: "Pollo", quantity: 200, unit: "g" },
      { emoji: "🌮", name: "Tortillas", quantity: 3, unit: "u" },
      { emoji: "🥬", name: "Lechuga", quantity: 30, unit: "g" },
      { emoji: "🧅", name: "Cebolla", quantity: 30, unit: "g" },
    ],
    steps: [
      "Cocinar el pollo en tiras.",
      "Calentar tortillas.",
      "Armar los tacos con pollo, lechuga y cebolla.",
    ],
  },
  {
    id: 11,
    name: "Salmón a la Plancha",
    image: require("../assets/dishes/salmon_plancha.jpg"),
    difficulty: "Media",
    time: "20'",
    proteins: "34g",
    calories: "350",
    price: 6200,
    ingredients: [
      { emoji: "🐟", name: "Salmón", quantity: 200, unit: "g" },
      { emoji: "🍋", name: "Limón", quantity: 1, unit: "u" },
      { emoji: "🌿", name: "Eneldo", quantity: 1, unit: "cda" },
    ],
    steps: [
      "Sazonar el salmón.",
      "Cocinar por ambos lados hasta dorar.",
      "Agregar limón y eneldo antes de servir.",
    ],
  },
  {
    id: 12,
    name: "Puré de Papas",
    image: require("../assets/dishes/pure_papas.jpg"),
    difficulty: "Baja",
    time: "25'",
    proteins: "4g",
    calories: "220",
    price: 1500,
    ingredients: [
      { emoji: "🥔", name: "Papas", quantity: 300, unit: "g" },
      { emoji: "🥛", name: "Leche", quantity: 50, unit: "ml" },
      { emoji: "🧈", name: "Mantequilla", quantity: 20, unit: "g" },
    ],
    steps: [
      "Cocinar papas en agua.",
      "Moldear con mantequilla.",
      "Agregar leche hasta textura deseada.",
    ],
  },
  {
    id: 13,
    name: "Hamburguesa Casera",
    image: require("../assets/dishes/hamburguesa.jpg"),
    difficulty: "Media",
    time: "30'",
    proteins: "25g",
    calories: "520",
    price: 4800,
    ingredients: [
      { emoji: "🥩", name: "Carne molida", quantity: 200, unit: "g" },
      { emoji: "🍞", name: "Pan de hamburguesa", quantity: 1, unit: "u" },
      { emoji: "🧀", name: "Queso", quantity: 20, unit: "g" },
      { emoji: "🥬", name: "Lechuga", quantity: 20, unit: "g" },
    ],
    steps: [
      "Formar la hamburguesa con la carne.",
      "Cocinar en sartén.",
      "Armar con pan, queso y verduras.",
    ],
  },
  {
    id: 14,
    name: "Pizza Margarita",
    image: require("../assets/dishes/pizza_margarita.jpg"),
    difficulty: "Media",
    time: "30'",
    proteins: "15g",
    calories: "600",
    price: 6500,
    ingredients: [
      { emoji: "🍕", name: "Masa de pizza", quantity: 1, unit: "u" },
      { emoji: "🍅", name: "Salsa de tomate", quantity: 100, unit: "g" },
      { emoji: "🧀", name: "Mozzarella", quantity: 120, unit: "g" },
      { emoji: "🌿", name: "Albahaca", quantity: 5, unit: "g" },
    ],
    steps: [
      "Extender la masa y agregar la salsa.",
      "Cubrir con mozzarella.",
      "Hornear por 12 minutos y agregar albahaca.",
    ],
  },
  {
    id: 15,
    name: "Empanadas de Queso",
    image: require("../assets/dishes/empanadas_queso.jpg"),
    difficulty: "Media",
    time: "25'",
    proteins: "10g",
    calories: "340",
    price: 3000,
    ingredients: [
      { emoji: "🥐", name: "Masa de empanada", quantity: 2, unit: "u" },
      { emoji: "🧀", name: "Queso", quantity: 80, unit: "g" },
      { emoji: "🫒", name: "Aceite", quantity: 300, unit: "ml" },
    ],
    steps: [
      "Rellenar las masas con queso.",
      "Cerrar bordes.",
      "Freír hasta dorar.",
    ],
  },
  {
    id: 16,
    name: "Galletas Caseras",
    image: require("../assets/dishes/galletas.jpg"),
    difficulty: "Baja",
    time: "20'",
    proteins: "4g",
    calories: "240",
    price: 1700,
    ingredients: [
      { emoji: "🌾", name: "Harina", quantity: 120, unit: "g" },
      { emoji: "🧈", name: "Mantequilla", quantity: 60, unit: "g" },
      { emoji: "🍬", name: "Azúcar", quantity: 50, unit: "g" },
    ],
    steps: [
      "Mezclar ingredientes secos.",
      "Integrar mantequilla.",
      "Formar galletas y hornear 10 minutos.",
    ],
  },
  {
    id: 17,
    name: "Arroz Chaufa",
    image: require("../assets/dishes/arroz_chaufa.jpg"),
    difficulty: "Media",
    time: "25'",
    proteins: "20g",
    calories: "520",
    price: 5200,
    ingredients: [
      { emoji: "🍚", name: "Arroz cocido", quantity: 200, unit: "g" },
      { emoji: "🥩", name: "Carne o pollo", quantity: 150, unit: "g" },
      { emoji: "🥚", name: "Huevo", quantity: 1, unit: "u" },
      { emoji: "🧅", name: "Cebollín", quantity: 20, unit: "g" },
    ],
    steps: [
      "Saltear la carne.",
      "Agregar arroz y mezclar.",
      "Añadir huevo revuelto.",
      "Agregar cebollín y servir.",
    ],
  },
  {
    id: 18,
    name: "Crema de Zapallo",
    image: require("../assets/dishes/crema_zapallo.jpg"),
    difficulty: "Baja",
    time: "20'",
    proteins: "3g",
    calories: "140",
    price: 2600,
    ingredients: [
      { emoji: "🎃", name: "Zapallo", quantity: 300, unit: "g" },
      { emoji: "🧅", name: "Cebolla", quantity: 40, unit: "g" },
      { emoji: "🥣", name: "Caldo", quantity: 200, unit: "ml" },
    ],
    steps: [
      "Cocinar zapallo y cebolla.",
      "Licuar con caldo.",
      "Servir caliente.",
    ],
  },
  {
    id: 19,
    name: "Fajitas de Res",
    image: require("../assets/dishes/fajitas_res.jpg"),
    difficulty: "Media",
    time: "30'",
    proteins: "26g",
    calories: "480",
    price: 5200,
    ingredients: [
      { emoji: "🥩", name: "Carne de res", quantity: 220, unit: "g" },
      { emoji: "🌮", name: "Tortillas", quantity: 3, unit: "u" },
      { emoji: "🫑", name: "Pimentón", quantity: 40, unit: "g" },
    ],
    steps: [
      "Saltear carne y pimentón.",
      "Calentar tortillas.",
      "Armar fajitas y servir.",
    ],
  },
  {
    id: 20,
    name: "Lentejas Guisadas",
    image: require("../assets/dishes/lentejas.jpg"),
    difficulty: "Media",
    time: "40'",
    proteins: "18g",
    calories: "380",
    price: 3100,
    ingredients: [
      { emoji: "🌰", name: "Lentejas", quantity: 200, unit: "g" },
      { emoji: "🥕", name: "Zanahoria", quantity: 50, unit: "g" },
      { emoji: "🧅", name: "Cebolla", quantity: 40, unit: "g" },
    ],
    steps: [
      "Remojar lentejas.",
      "Cocinar con verduras.",
      "Sazonar y servir.",
    ],
  },
  {
    id: 21,
    name: "Cazuela",
    image: require("../assets/dishes/cazuela.jpg"),
    difficulty: "Media",
    time: "50'",
    proteins: "22g",
    calories: "480",
    price: 5200,
    ingredients: [
      { emoji: "🍖", name: "Carne", quantity: 250, unit: "g" },
      { emoji: "🥔", name: "Papas", quantity: 150, unit: "g" },
      { emoji: "🥕", name: "Zanahoria", quantity: 60, unit: "g" },
      { emoji: "🌽", name: "Choclo", quantity: 80, unit: "g" },
    ],
    steps: [
      "Cocinar carne con agua.",
      "Agregar verduras según su dureza.",
      "Cocinar hasta ablandar y servir.",
    ],
  },
  {
    id: 22,
    name: "Charquicán",
    image: require("../assets/dishes/charquican.jpg"),
    difficulty: "Media",
    time: "35'",
    proteins: "18g",
    calories: "430",
    price: 4200,
    ingredients: [
      { emoji: "🥩", name: "Carne molida", quantity: 180, unit: "g" },
      { emoji: "🥔", name: "Papas", quantity: 200, unit: "g" },
      { emoji: "🫛", name: "Porotos verdes", quantity: 50, unit: "g" },
      { emoji: "🧅", name: "Cebolla", quantity: 40, unit: "g" },
    ],
    steps: [
      "Saltear carne con cebolla.",
      "Agregar papas y agua.",
      "Añadir porotos y cocinar todo.",
    ],
  }

];
