
export const mealsData = [
  {
    id: 1,
    name: "Papas Fritas",
    image: require("../assets/dishes/papas_fritas.jpg"),
    difficulty: "Baja",
    time: "20'",
    proteins: "5g",
    calories: "312",
    price: 2500,
    ingredients: [
      { emoji: "🥔", name: "Papas", quantity: 300, unit: "g" },
      { emoji: "🧂", name: "Sal", quantity: 1, unit: "pizca" },
      { emoji: "🥄", name: "Aceite", quantity: 200, unit: "ml" },
    ],
    steps: [
      "Lavar y pelar las papas.",
      "Cortarlas en bastones.",
      "Freír en aceite caliente hasta que estén doradas.",
      "Escurrir y agregar sal al gusto.",
    ],
  },
  {
    id: 2,
    name: "Ensalada César",
    image: require("../assets/dishes/ensalada_cesar.jpg"),
    difficulty: "Baja",
    time: "15'",
    proteins: "12g",
    calories: "180",
    price: 4200,
    ingredients: [
      { emoji: "🥬", name: "Lechuga romana", quantity: 100, unit: "g" },
      { emoji: "🍗", name: "Pechuga de pollo", quantity: 120, unit: "g" },
      { emoji: "🧀", name: "Queso parmesano", quantity: 30, unit: "g" },
      { emoji: "🍞", name: "Crutones", quantity: 50, unit: "g" },
      { emoji: "🥣", name: "Aderezo César", quantity: 30, unit: "ml" },
    ],
    steps: [
      "Lavar y cortar la lechuga.",
      "Cocinar el pollo a la plancha y cortarlo en tiras.",
      "Agregar crutones y queso parmesano.",
      "Incorporar el aderezo y mezclar bien antes de servir.",
    ],
  },
  {
    id: 3,
    name: "Pollo al Horno",
    image: require("../assets/dishes/pollo_al_horno.jpg"),
    difficulty: "Media",
    time: "45'",
    proteins: "35g",
    calories: "400",
    price: 5500,
    ingredients: [
      { emoji: "🍗", name: "Pollo", quantity: 250, unit: "g" },
      { emoji: "🥔", name: "Papas", quantity: 200, unit: "g" },
      { emoji: "🧄", name: "Ajo", quantity: 2, unit: "dientes" },
      { emoji: "🌿", name: "Hierbas", quantity: 1, unit: "cda" },
      { emoji: "🥄", name: "Aceite de oliva", quantity: 20, unit: "ml" },
    ],
    steps: [
      "Precalentar el horno a 200°C.",
      "Colocar el pollo y las papas en una bandeja.",
      "Añadir ajo, hierbas y aceite de oliva.",
      "Hornear por 40-45 minutos hasta que esté dorado.",
    ],
  },
];
